---
pod_name: DC2_POD1

max_l3leaf_to_spine_links: 4
mgmt_gateway: 10.6.65.1
mgmt_interface: Management0
mgmt_interface_vrf: mgmt
mgmt_destination_networks:
  - 0.0.0.0/0
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: "64800"
    loopback_ipv4_pool: 10.4.64.0/24
    uplink_interfaces: ['Ethernet29/1', 'Ethernet30/1', 'Ethernet31/1', 'Ethernet32/1']
    uplink_switches: ['SUPER-SPINE1', 'SUPER-SPINE2', 'SUPER-SPINE3', 'SUPER-SPINE4']
    uplink_switch_interfaces: ['Ethernet17/1', 'Ethernet17/2',
                               'Ethernet17/3', 'Ethernet17/4',
                               'Ethernet18/1', 'Ethernet18/2',
                               'Ethernet18/3', 'Ethernet18/4',
                               'Ethernet19/1', 'Ethernet19/2',
                               'Ethernet19/3', 'Ethernet19/4',
                               'Ethernet20/1', 'Ethernet20/2',
                               'Ethernet20/3', 'Ethernet20/4']
    max_uplink_switches: 4
    uplink_ipv4_pool: 172.16.32.0/24
    uplink_ptp:
      enable: true
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
  nodes:
    DC2-POD1-SPINE1:
      id: 10
      bgp_as: "64801"
      mgmt_ip: "{{ ansible_host }}/24"
      evpn_role: none
      # next line specifies interface on SS
      uplink_switch_interfaces: ['Ethernet9/1', 'Ethernet9/1', 'Ethernet9/1', 'Ethernet9/1']
    DC2-POD1-SPINE2:
      id: 12
      bgp_as: "64802"
      evpn_role: none
      mgmt_ip: "{{ ansible_host }}/24"
      uplink_switch_interfaces: ['Ethernet10/1', 'Ethernet10/1', 'Ethernet10/1', 'Ethernet10/1']
    DC2-POD1-SPINE3:
      id: 13
      bgp_as: "64803"
      evpn_role: none
      mgmt_ip: "{{ ansible_host }}/24"
      uplink_switch_interfaces: ['Ethernet11/1', 'Ethernet11/1', 'Ethernet11/1', 'Ethernet11/1']
    DC2-POD1-SPINE4:
      id: 14
      bgp_as: "64804"
      evpn_role: none
      mgmt_ip: "{{ ansible_host }}/24"
      uplink_switch_interfaces: ['Ethernet12/1', 'Ethernet12/1', 'Ethernet12/1', 'Ethernet12/1']

# In DC2 we define all variables via defaults
l3leaf:
  defaults:
    bgp_as: 65100
    virtual_router_mac_address: 00:1c:73:00:dc:21
    platform: vEOS-LAB
    evpn_role: none
    # evpn_route_servers: [ DC2-POD1-LEAF1A, DC2-POD1-LEAF1B ]
    spanning_tree_mode: rstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 10.4.65.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.5.65.0/24
    uplink_ipv4_pool: 172.17.64.0/24
    uplink_ptp:
      enable: true
    uplink_interfaces: ['Ethernet29/1', 'Ethernet30/1', 'Ethernet31/1', 'Ethernet32/1']
    uplink_switches: ['DC2-POD1-SPINE1', 'DC2-POD1-SPINE2', 'DC2-POD1-SPINE3', 'DC2-POD1-SPINE4']
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
      # filter matches tags specified in TENANT_NETWORKS.yml. This is where we associate vrfs/racks.
      # Vlans in servers would match specific nodes. I'll have to check 'tag' capabilites there
    filter:
      always_include_vrfs_in_tenants: ['all'] # Testing that we configure all VRFs even with no VLANs.
      tags: ['all']
    raw_eos_cli: |
      interface Loopback1010
        description Loopback created from raw_eos_cli under l3leaf defaults in DC2 POD1
    mlag: true
    mlag_interfaces: [Ethernet15/1, Ethernet16/1]
    mlag_peer_l3_ipv4_pool: 172.19.64.0/24
    mlag_peer_ipv4_pool: 172.19.65.0/24
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: none
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
  node_groups:
    RACK1_MLAG:
      platform: vEOS-LAB
      bgp_as: "65101"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      # evpn_role: server
      filter:
        tenants: [Cust_A, Cust_B]
        tags: [Cust_B_opzone]
        # Testing that we respect the empty tenants list, so no VRFs will be configured.
        always_include_vrfs_in_tenants: ['all']
      nodes:
        DC2-POD1-LEAF1A:
          id: 20
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1, Ethernet1/1, Ethernet1/1]
        DC2-POD1-LEAF1B:
          id: 21
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet2/1, Ethernet2/1, Ethernet2/1, Ethernet2/1]
    RACK2_MLAG:
      platform: vEOS-LAB
      bgp_as: "65102"
      # evpn_role: server
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF2A:
          structured_config:
            domain_list:
              - structured-config.set.on.node
          id: 23
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet3/1, Ethernet3/1, Ethernet3/1, Ethernet3/1]
        DC2-POD1-LEAF2B:
          id: 24
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet4/1, Ethernet4/1, Ethernet4/1, Ethernet4/1]
    RACK3_MLAG:
      platform: vEOS-LAB
      bgp_as: "65103"
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF3A:
          id: 25
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet5/1, Ethernet5/1, Ethernet5/1, Ethernet5/1]
        DC2-POD1-LEAF3B:
          id: 26
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet6/1, Ethernet6/1, Ethernet6/1, Ethernet6/1]
    RACK4_MLAG:
      platform: vEOS-LAB
      bgp_as: "65104"
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF4A:
          id: 27
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet7/1, Ethernet7/1, Ethernet7/1, Ethernet7/1]
        DC2-POD1-LEAF4B:
          id: 28
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet8/1, Ethernet8/1, Ethernet8/1, Ethernet8/1]
    RACK5_MLAG:
      platform: vEOS-LAB
      bgp_as: "65105"
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF5A:
          id: 29
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet9/1, Ethernet9/1, Ethernet9/1, Ethernet9/1]
        DC2-POD1-LEAF5B:
          id: 30
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet10/1, Ethernet10/1, Ethernet10/1, Ethernet10/1]
    RACK6_MLAG:
      bgp_as: "65106"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF6A:
          id: 31
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet11/1, Ethernet11/1, Ethernet11/1, Ethernet11/1]
        DC2-POD1-LEAF6B:
          id: 32
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet12/1, Ethernet12/1, Ethernet12/1, Ethernet12/1]
    RACK7_MLAG:
      bgp_as: "65107"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF7A:
          id: 33
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet13/1, Ethernet13/1, Ethernet13/1, Ethernet13/1]
        DC2-POD1-LEAF7B:
          id: 34
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet14/1, Ethernet14/1, Ethernet14/1, Ethernet14/1]
    RACK8_MLAG:
      bgp_as: "65108"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF8A:
          id: 35
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet15/1, Ethernet15/1, Ethernet15/1, Ethernet15/1]
        DC2-POD1-LEAF8B:
          id: 36
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet16/1, Ethernet16/1, Ethernet16/1, Ethernet16/1]
    RACK9_MLAG:
      bgp_as: "65109"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF9A:
          id: 37
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet17/1, Ethernet17/1, Ethernet17/1, Ethernet17/1]
        DC2-POD1-LEAF9B:
          id: 38
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet18/1, Ethernet18/1, Ethernet18/1, Ethernet18/1]
    RACK10_MLAG:
      bgp_as: "65110"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF10A:
          id: 39
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet19/1, Ethernet19/1, Ethernet19/1, Ethernet19/1]
        DC2-POD1-LEAF10B:
          id: 40
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet20/1, Ethernet20/1, Ethernet20/1, Ethernet20/1]
    RACK11_MLAG:
      bgp_as: "65111"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF11A:
          id: 41
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet21/1, Ethernet21/1, Ethernet21/1, Ethernet21/1]
        DC2-POD1-LEAF11B:
          id: 42
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet22/1, Ethernet22/1, Ethernet22/1, Ethernet22/1]
    RACK12_MLAG:
      bgp_as: "65112"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF12A:
          id: 43
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet23/1, Ethernet23/1, Ethernet23/1, Ethernet23/1]
        DC2-POD1-LEAF12B:
          id: 44
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet24/1, Ethernet24/1, Ethernet24/1, Ethernet24/1]
    RACK13_MLAG:
      bgp_as: "65113"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF13A:
          id: 45
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet25/1, Ethernet25/1, Ethernet25/1, Ethernet25/1]
        DC2-POD1-LEAF13B:
          id: 46
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet26/1, Ethernet26/1, Ethernet26/1, Ethernet26/1]
    RACK14_MLAG:
      bgp_as: "65114"
      mlag: true
      mlag_dual_primary_detection: true
      mlag_peer_l3_vlan: 4094 # Using 4094 for both mlag peer and l3 peerings.
      nodes:
        DC2-POD1-LEAF14A:
          id: 47
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet27/1, Ethernet27/1, Ethernet27/1, Ethernet27/1]
        DC2-POD1-LEAF14B:
          id: 48
          mgmt_ip: "{{ ansible_host }}/24"
          uplink_switch_interfaces: [Ethernet28/1, Ethernet28/1, Ethernet28/1, Ethernet28/1]
# In DC2 we define all variables via defaults if possible
l2leaf:
  defaults:
    inband_management_subnet: 172.21.210.0/24
    platform: vEOS-LAB
    uplink_interfaces: [Ethernet1]
    spanning_tree_mode: mstp
    spanning_tree_priority: 8192
    mlag: false
    raw_eos_cli: |
      interface Loopback1011
        description Loopback created from raw_eos_cli under l2leaf defaults in DC2 POD1
  node_groups:
    RACK1_SINGLE:
      uplink_switches: ['DC2-POD1-LEAF1A']
      nodes:
        DC2-POD1-L2LEAF1A:
          id: 51
          mgmt_ip: 192.168.1.23/24
          uplink_switch_interfaces: ['Ethernet3']
